### ISSUE TITLE
Dockerが初めてのWindowsユーザー向け手順

### ISSUE THREAD

**Issue by michi-rgb** [yellowshippo/isogcn-iclr2021#1]
GitHubのコードをダウンロード・展開
https://github.com/yellowshippo/isogcn-iclr2021

Makefileがあるディレクトリに「images」というフォルダを作成

Dockerイメージをダウンロード(Windowsエクスプローラーでは展開しない)し、作成した「images」フォルダに格納
https://savanna.ritc.jp/~horiem/isogcn_iclr2021/images/isogcn.tar

Docker Desktopをダウンロード・インストール
https://www.docker.com/ja-jp/

Make for Windowsをダウンロード・インストール
https://gnuwin32.sourceforge.net/packages/make.htm

Docker Desktopを起動・ログイン

コマンドプロンプトを起動

コマンドプロンプトの「cd 〜」コマンドで、ダウンロードしたGitHubコードのMakefileがあるディレクトリに移動

コマンドプロンプトの「make in」コマンドで、Makefile内のin段落に紐づけられたdockerコマンドを実行
(内容：tarファイルをDockerイメージに変換→指定されたDockerイメージを使って、GPUサポートがあり、インタラクティブなBashシェルを起動)

**Comment by yellowshippo** [comment]
Thank you for the comment.

情報をいただきありがとうございます。
